from __future__ import annotations

import json
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
AUDIT_SCRIPT = REPO_ROOT / ".claude" / "skills" / "codebase-audit" / "scripts" / "audit.py"


def run_git(repo: Path, *args: str) -> None:
    subprocess.run(
        ["git", *args],
        cwd=repo,
        text=True,
        capture_output=True,
        check=True,
    )


def init_repo(repo: Path) -> None:
    run_git(repo, "init", "-q")
    run_git(repo, "config", "user.email", "audit-tests@example.com")
    run_git(repo, "config", "user.name", "Audit Tests")


def write_file(repo: Path, rel_path: str, content: str) -> None:
    path = repo / rel_path
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def commit_all(repo: Path, message: str) -> None:
    run_git(repo, "add", ".")
    run_git(repo, "commit", "-q", "-m", message)


class CodebaseAuditScriptTests(unittest.TestCase):
    def run_audit(self, repo: Path, *args: str) -> subprocess.CompletedProcess[str]:
        result = subprocess.run(
            [sys.executable, str(AUDIT_SCRIPT), "--repo", str(repo), *args],
            text=True,
            capture_output=True,
            check=False,
        )
        self.assertEqual(result.returncode, 0, result.stderr + result.stdout)
        return result

    def test_json_output_reports_python_metrics_and_skips_generated_files(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            repo = Path(tmp)
            init_repo(repo)
            write_file(
                repo,
                "src/example.py",
                "\n".join(
                    [
                        "class Example:",
                        "    def small(self):",
                        "        return 1",
                        "",
                        "def big():",
                        "    total = 0",
                        "    for value in range(3):",
                        "        total += value",
                        "    return total",
                        "",
                    ]
                ),
            )
            write_file(
                repo,
                "src/generated.py",
                "# Generated by fixture tool\n\ndef generated():\n    return 1\n",
            )
            commit_all(repo, "initial")

            result = self.run_audit(repo, "--json", "--since-days", "999")

        payload = json.loads(result.stdout)
        self.assertEqual(payload["meta"]["languages"], {"python": 1})
        self.assertEqual(payload["meta"]["generated"], 1)

        files = payload["files"]
        self.assertEqual([file["path"] for file in files], ["src/example.py"])
        self.assertEqual(files[0]["longest_func"], "big")
        self.assertGreater(files[0]["longest_func_lines"], 0)
        self.assertGreater(files[0]["n_decls"], 1)

    def test_staged_mode_reports_only_staged_source_files_without_blocking(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            repo = Path(tmp)
            init_repo(repo)
            write_file(repo, "src/a.py", "def existing():\n    return 1\n")
            commit_all(repo, "initial")
            write_file(repo, "src/new_file.py", "def added():\n    return 2\n")
            run_git(repo, "add", "src/new_file.py")

            result = self.run_audit(repo, "--staged")

        self.assertIn("codebase-audit · 1 source file(s) changed", result.stdout)
        self.assertIn("advisory, non-blocking", result.stdout)

    def test_temporal_coupling_reports_files_changed_together(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            repo = Path(tmp)
            init_repo(repo)
            for index in range(4):
                write_file(repo, "src/a.py", f"def a():\n    return {index}\n")
                write_file(repo, "tests/b.py", f"def b():\n    return {index}\n")
                commit_all(repo, f"coupled {index}")

            result = self.run_audit(
                repo,
                "--json",
                "--since-days",
                "999",
                "--module-depth",
                "1",
            )

        payload = json.loads(result.stdout)
        pairs = {(item["a"], item["b"]): item for item in payload["coupling"]}
        pair = pairs[("src/a.py", "tests/b.py")]
        self.assertEqual(pair["n"], 4)
        self.assertEqual(pair["ab"], 1.0)
        self.assertEqual(pair["ba"], 1.0)
        self.assertTrue(pair["cross"])


if __name__ == "__main__":
    unittest.main()
