#!/usr/bin/env python3
"""codebase-audit — emit ranked, evidence-rich health signals for an agent to judge.

NOT a gate and NOT a linter. It does the wide, quantitative gathering an agent
cannot cheaply do itself (it would have to read every file and run git log, burning
the context window) and prints a compact, ranked digest. The agent reads it and
decides what — if anything — to refactor. The script never says "too big"; it says
"here is where the mass, the change, and the coupling are, with evidence."

Fully repo-agnostic — drop it into any git repo and run it; no config, no setup.
Discovery is `git ls-files` (the version-controlled working tree), language is
detected by extension from a data-driven registry, and machine-generated files are
skipped via the universal `@generated` / "Generated by" / "Code generated" marker.

Signals (why each is here):
  * Decomposed size — raw LOC is the least informative number. A 790-line file that
    is 22 small types (a registry) is healthy; one where a single function is 400
    lines is not. So we emit LOC, largest-symbol span, biggest single function
    (`maxFn`), decl count, god ratio, nesting and density — measured at every depth
    so "big but flat" (many small methods) vs. "big & tangled" (one giant method)
    are actually distinguishable, which is the whole point.
  * Git-temporal — the half a static linter is blind to. churn, hotspot (size x
    churn — the classic "look here first"), and temporal coupling (files that always
    change together reveal a module boundary the directory tree doesn't show). This
    is established behavioral-code-analysis (CodeScene / Tornhill, Code as a Crime
    Scene), not invention.
  * Percentile ranking — "p99 LOC for this language" self-calibrates to the repo.

Symbol sizing is brace-/indentation-based and approximate (it says so in the
report). Function-level sizing needs a function *keyword*; languages without one
(C/C++, Java, C#) get type-level sizing only — their `maxFn` stays blank.

Stdlib only. Run from the repo root.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from collections import defaultdict
from dataclasses import dataclass, field
from pathlib import Path

# --------------------------------------------------------------------------- #
# Language registry — add a language by adding one row.                       #
# --------------------------------------------------------------------------- #
# style: "brace" (size symbols by { } depth) | "indent" (by indentation).
# decl:  regex with group(1)=kind, group(2)=name, or None (file-level metrics only).
#        Matched at every nesting level, so methods inside a type are measured too.
# funcs: which kinds count as "functions" for the biggest-function signal.
# A leading "(?:\w+\s+)*?" lazily skips modifier words (pub, final, nonisolated,
# export, async, ...) so we don't enumerate every language's modifier zoo.

_MODS = r"(?:@[\w.]+(?:\([^)]*\))?\s+)*(?:\w+\s+)*?"

# Function/method detector for keyword-less languages (TS/JS/Java/C#), where a
# function is `name(args) … {` or `const name = (…) => {` rather than `func name`.
# High-precision on purpose: it requires the body brace to open at end of line and
# excludes control keywords, so `if (x) {`, calls, plain `let x = 0`, and arrow
# callbacks don't masquerade as functions. It will miss bodies whose `{` is on the
# next line — a gap is safer than a false signal. group(1)=arrow-const name (or
# None), group(2)=method name (or None).
_METHOD = re.compile(
    r"^\s*(?:"
    # const/let/var NAME = (…) => {  |  = async (…) => {  |  = function  |  = x => {
    r"(?:export\s+)?(?:const|let|var)\s+([A-Za-z_$][\w$]*)\s*(?::\s*[^=]+?)?=\s*(?:async\s+)?"
    r"(?:function\b|[\w$]*\s*=>|\([^()]*\)\s*(?::[^={]+)?=>)[^{};]*\{\s*$"
    r"|"
    # [modifiers] [return-type] NAME(args) … {   (class / object method)
    r"(?:(?:public|private|protected|internal|static|final|abstract|virtual|override|"
    r"async|get|set|readonly|export|default|sealed|partial|new)\s+)*"
    r"(?:[\w<>\[\].,&*:]+\s+)?"
    r"(?!(?:if|for|while|switch|catch|return|else|do|with|new|typeof|await|throw|case|in|of|function)\b)"
    r"([A-Za-z_$][\w$]*)\s*\([^;{}]*\)\s*[^{};]*\{\s*$"
    r")")


@dataclass
class Lang:
    exts: tuple
    comment: str
    style: str
    decl: object = None
    funcs: frozenset = frozenset()
    imp: object = None
    method: object = None      # keyword-less method shape (TS/JS/Java/C#); optional


def _c(p):
    return re.compile(p) if p else None


LANGS = {
    "python": Lang((".py",), "#", "indent",
                   _c(r"^(async def|def|class)\s+(\w+)"), frozenset({"def", "async def"}),
                   _c(r"^\s*(?:from\s+([.\w]+)\s+import|import\s+([.\w]+))")),
    "swift": Lang((".swift",), "//", "brace",
                  _c(rf"^\s*{_MODS}\b(struct|class|enum|actor|protocol|extension|func)\s+([\w.]+)"),
                  frozenset({"func"}), _c(r"^\s*import\s+(\w+)")),
    # TS/JS use explicit prefixes (not the lazy word-skip) so `for (const x of …)`
    # and `if (let …)` aren't mistaken for top-level const/let declarations.
    # const/let are NOT type/function kinds here (they'd catch local variables and
    # inflate decl counts); genuine arrow-function consts are caught by _METHOD.
    "ts": Lang((".ts", ".tsx", ".mts", ".cts"), "//", "brace",
               _c(r"^\s*(?:export\s+)?(?:default\s+)?(?:declare\s+)?(?:abstract\s+)?"
                  r"(function|class|interface|type|enum)\s*\*?\s+(\w+)"),
               frozenset({"function"}), _c(r"""^\s*import\s+.*?from\s+['"]([^'"]+)['"]"""), _METHOD),
    "js": Lang((".js", ".jsx", ".mjs", ".cjs"), "//", "brace",
               _c(r"^\s*(?:export\s+)?(?:default\s+)?(function|class)\s*\*?\s+(\w+)"),
               frozenset({"function"}), _c(r"""^\s*import\s+.*?from\s+['"]([^'"]+)['"]"""), _METHOD),
    "go": Lang((".go",), "//", "brace",
               _c(r"^\s*(func|type)\s+(?:\([^)]*\)\s*)?(\w+)"), frozenset({"func"}),
               _c(r'^\s*(?:[\w.]+\s+)?"([^"]+)"')),
    "rust": Lang((".rs",), "//", "brace",
                 _c(rf"^\s*{_MODS}\b(fn|struct|enum|trait|impl|mod)\s+(\w+)"),
                 frozenset({"fn"}), _c(r"^\s*use\s+([\w:]+)")),
    "java": Lang((".java",), "//", "brace",
                 _c(rf"^\s*{_MODS}\b(class|interface|enum|record)\s+(\w+)"),
                 frozenset(), _c(r"^\s*import\s+([\w.]+)"), _METHOD),
    "kotlin": Lang((".kt", ".kts"), "//", "brace",
                   _c(rf"^\s*{_MODS}\b(fun|class|object|interface)\s+(\w+)"),
                   frozenset({"fun"}), _c(r"^\s*import\s+([\w.]+)")),
    "cpp": Lang((".c", ".h", ".cc", ".cpp", ".cxx", ".hpp", ".hh"), "//", "brace",
                _c(rf"^\s*{_MODS}\b(class|struct|enum|namespace|union)\s+(\w+)"),
                frozenset(), _c(r'^\s*#\s*include\s+[<"]([^>"]+)')),
    "csharp": Lang((".cs",), "//", "brace",
                   _c(rf"^\s*{_MODS}\b(class|interface|enum|struct|record)\s+(\w+)"),
                   frozenset(), _c(r"^\s*using\s+([\w.]+)"), _METHOD),
    "ruby": Lang((".rb",), "#", "indent",
                 _c(r"^(def|class|module)\s+([\w.:?!=]+)"), frozenset({"def"}),
                 _c(r"""^\s*require(?:_relative)?\s+['"]([^'"]+)""")),
}
EXT_TO_LANG = {ext: name for name, spec in LANGS.items() for ext in spec.exts}

IGNORE_DIRS = {".git", ".venv", "venv", "__pycache__", "node_modules", "build",
               "dist", "DerivedData", ".build", "coverage", ".next", "Pods",
               ".mypy_cache", ".pytest_cache"}
MAX_FILE_BYTES = 1_500_000

# Universal "this file is machine-generated" markers (GitHub linguist / Go / etc.).
# Requires a real comment prefix and a *qualified* "generated" phrase, anchored at
# line start, checked only in the file's head — so authored prose that merely
# mentions "generated" or "do not edit" isn't mistaken for a generated blob.
_GENERATED = re.compile(
    r"(?i)^\s*(?://+|#+|/\*+|\*+|--+|;+|<!--)\s*"
    r"(?:@generated\b|generated by\b|code generated\b|auto-?generated\b"
    r"|automatically generated\b|this file (?:is|was) (?:auto(?:matically)?[ -]?)?generated\b)")


def _looks_generated(head: str) -> bool:
    return any(_GENERATED.match(line) for line in head.splitlines()[:5])


# Coupling thresholds (behavioral-code-analysis defaults).
COUPLING_SUPPORT = 4          # ignore pairs seen fewer than this many times
COUPLING_RATIO = 0.5          # report only strong co-change
COUPLING_MAX_PER_COMMIT = 40  # bulk/mechanical commits aren't real coupling


# --------------------------------------------------------------------------- #
# Data model                                                                  #
# --------------------------------------------------------------------------- #

@dataclass
class FileRec:
    path: str
    lang: str
    loc: int = 0           # non-blank lines
    total_lines: int = 0
    code: int = 0
    comment: int = 0
    density: float = 0.0
    n_decls: int = 0
    largest_symbol: str = ""
    largest_symbol_lines: int = 0   # non-blank lines in the biggest symbol
    longest_func: str = ""
    longest_func_lines: int = 0     # non-blank lines in the biggest function
    max_nesting: int = 0
    n_imports: int = 0
    todo: int = 0
    churn: int = 0
    authors: int = 0
    last_touched_days: "int | None" = None
    god_ratio: float = 0.0
    hotspot: int = 0
    pct: dict = field(default_factory=dict)


# --------------------------------------------------------------------------- #
# Discovery (git working tree, with a filesystem fallback)                     #
# --------------------------------------------------------------------------- #

def discover(repo: Path, paths, only_lang):
    """Return ([(rel_path, lang)], coverage). Coverage is honest about what was
    skipped (generated / oversized) so a partial scan never reads as 'covered
    everything'."""
    files = git_tree(repo)
    if files is None:                       # not a git repo — walk the filesystem
        files = []
        for p in repo.rglob("*"):
            if p.is_file() and not any(part in IGNORE_DIRS for part in p.parts):
                files.append(str(p.relative_to(repo)))
    out = []
    cov = {"skipped_big": 0, "generated": 0, "by_lang": defaultdict(int),
           "roots": set(), "unknown_ext": 0}
    for rel in files:
        relp = rel.replace("\\", "/")
        lang = EXT_TO_LANG.get(Path(rel).suffix)
        if lang is None:
            cov["unknown_ext"] += 1
            continue
        if only_lang and lang != only_lang:
            continue
        if paths and not any(relp.startswith(pre) for pre in paths):
            continue
        ap = repo / rel
        try:
            if ap.stat().st_size > MAX_FILE_BYTES:
                cov["skipped_big"] += 1
                continue
            head = ap.open("r", encoding="utf-8", errors="replace").read(2048)
        except OSError:
            continue
        if _looks_generated(head):
            cov["generated"] += 1
            continue
        out.append((rel, lang))
        cov["by_lang"][lang] += 1
        cov["roots"].add(Path(rel).parts[0] if len(Path(rel).parts) > 1 else ".")
    return out, cov


def git_tree(repo: Path):
    try:
        out = subprocess.run(
            ["git", "ls-files", "--cached", "--others", "--exclude-standard"],
            cwd=repo, capture_output=True, text=True, timeout=60)
        return [l for l in out.stdout.splitlines() if l.strip()] if out.returncode == 0 else None
    except (subprocess.SubprocessError, OSError):
        return None


# --------------------------------------------------------------------------- #
# Static analysis                                                             #
# --------------------------------------------------------------------------- #

def strip_strings(line, ml, comment):
    """Remove string / char / template / comment content (tracking multi-line
    strings and block comments across lines via `ml`) so their braces never skew
    brace-depth. Returns (code_only, new_ml). This is what makes brace sizing
    robust to template literals and triple-quoted strings."""
    out = []
    i, n = 0, len(line)
    while i < n:
        if ml is not None:                       # inside a multi-line string/comment
            j = line.find(ml, i)
            if j < 0:
                return "".join(out), ml
            i, ml = j + len(ml), None
            continue
        if comment and line.startswith(comment, i):
            break
        if line.startswith("/*", i):
            j = line.find("*/", i + 2)
            if j < 0:
                return "".join(out), "*/"
            i = j + 2
            continue
        if line.startswith('"""', i) or line.startswith("'''", i):
            t = line[i:i + 3]
            j = line.find(t, i + 3)
            if j < 0:
                return "".join(out), t
            i = j + 3
            continue
        ch = line[i]
        if ch in "\"'`":
            j = i + 1
            while j < n:
                if line[j] == "\\":
                    j += 2
                    continue
                if line[j] == ch:
                    break
                j += 1
            if j >= n:
                return "".join(out), ("`" if ch == "`" else None)
            i = j + 1
            continue
        out.append(ch)
        i += 1
    return "".join(out), ml


def _nb(cum, start, end):
    """Non-blank line count within [start, end] from a cumulative array."""
    return cum[end + 1] - cum[start]


def _record(rec, label, name, span, is_func):
    rec.n_decls += 1
    if span > rec.largest_symbol_lines:
        rec.largest_symbol_lines, rec.largest_symbol = span, f"{label} {name}"
    if is_func and span > rec.longest_func_lines:
        rec.longest_func_lines, rec.longest_func = span, name


def analyze_brace(rec, lines, spec, cum):
    """Size symbols by brace depth, at every nesting level (so a method inside a
    class is measured, not just the class). A pending decl attaches to the next
    `{`; its symbol closes when that brace's match is popped."""
    decl_re, funcs, comment, method_re = spec.decl, spec.funcs, spec.comment, spec.method
    depth = max_depth = 0
    ml = None
    pending = None      # (label, name, start, is_func) awaiting its opening brace
    stack = []          # one frame per open `{`: the decl that brace opened, or None
    for i, raw in enumerate(lines):
        incoming = ml
        code, ml = strip_strings(raw, ml, comment)
        if incoming is None:
            if decl_re and (m := decl_re.match(raw)):
                pending = (m.group(1), m.group(2), i, m.group(1) in funcs)
            elif method_re and (m := method_re.match(raw)):
                pending = ("func", m.group(1) or m.group(2), i, True)
        for ch in code:
            if ch == "{":
                stack.append(pending)
                pending = None
                depth += 1
                if depth > max_depth:
                    max_depth = depth
            elif ch == "}":
                if stack:
                    decl = stack.pop()
                    depth -= 1
                    if decl:
                        _record(rec, decl[0], decl[1], _nb(cum, decl[2], i), decl[3])
                elif depth > 0:
                    depth -= 1
    rec.max_nesting = max_depth


def analyze_indent(rec, lines, spec, cum):
    """Size def/class by indentation, at every level. A decl owns lines until the
    next non-blank, non-comment line at an equal-or-lower indent."""
    decl_re, funcs, marker = spec.decl, spec.funcs, spec.comment
    n = len(lines)
    decls = []
    for i, raw in enumerate(lines):
        s = raw.lstrip()
        if not s or s.startswith(marker):
            continue
        if m := decl_re.match(s):
            decls.append((m.group(1), m.group(2), i, len(raw) - len(s)))
    for kind, name, start, indent in decls:
        end = n - 1
        for j in range(start + 1, n):
            t = lines[j]
            ts = t.lstrip()
            if ts and not ts.startswith(marker) and len(t) - len(ts) <= indent:
                end = j - 1
                break
        while end > start and not lines[end].strip():
            end -= 1
        _record(rec, kind, name, _nb(cum, start, end), kind in funcs)
    max_indent = 0
    for raw in lines:
        s = raw.lstrip()
        if s and not s.startswith(marker):
            max_indent = max(max_indent, (len(raw) - len(s)) // 4)
    rec.max_nesting = max_indent


def analyze_file(repo, rel, lang):
    try:
        text = (repo / rel).read_text(encoding="utf-8", errors="replace")
    except OSError:
        return None
    spec = LANGS[lang]
    rec = FileRec(path=rel, lang=lang)
    lines = text.splitlines()
    rec.total_lines = len(lines)
    marker = spec.comment
    cum = [0] * (len(lines) + 1)        # cumulative non-blank line count
    nonblank_chars, in_block = 0, False
    for idx, raw in enumerate(lines):
        s = raw.strip()
        cum[idx + 1] = cum[idx] + (1 if s else 0)
        if not s:
            continue
        rec.loc += 1
        nonblank_chars += len(raw.rstrip())
        is_comment = False
        if spec.style == "brace" and ("/*" in s or in_block):
            is_comment = True
            if "/*" in s and "*/" not in s:
                in_block = True
            elif "*/" in s:
                in_block = False
        elif s.startswith(marker):
            is_comment = True
        rec.comment += is_comment
        rec.code += not is_comment
        if "TODO" in s or "FIXME" in s:
            rec.todo += 1
        if spec.imp and spec.imp.match(raw):
            rec.n_imports += 1
    (analyze_brace if spec.style == "brace" else analyze_indent)(rec, lines, spec, cum)
    rec.god_ratio = round(min(1.0, rec.largest_symbol_lines / rec.loc), 2) if rec.loc else 0.0
    rec.density = round(nonblank_chars / rec.loc, 1) if rec.loc else 0.0
    return rec


# --------------------------------------------------------------------------- #
# Git-temporal signals                                                        #
# --------------------------------------------------------------------------- #

def git_history(repo, since_days):
    try:
        out = subprocess.run(
            ["git", "log", f"--since={since_days} days ago", "--no-merges",
             "--name-only", "--pretty=format:\x01%an\x02%ct"],
            cwd=repo, capture_output=True, text=True, timeout=120).stdout
    except (subprocess.SubprocessError, OSError):
        return {}, {}, {}, {}, {}, None
    churn, authors, last_ts = defaultdict(int), defaultdict(set), {}
    pair, count = defaultdict(int), defaultdict(int)
    head_ts = author = ts = None
    files = []

    def flush():
        nonlocal files
        for f in files:
            churn[f] += 1
            authors[f].add(author)
            count[f] += 1
            if ts and (f not in last_ts or ts > last_ts[f]):
                last_ts[f] = ts
        if 1 < len(files) <= COUPLING_MAX_PER_COMMIT:
            u = sorted(set(files))
            for a in range(len(u)):
                for b in range(a + 1, len(u)):
                    pair[(u[a], u[b])] += 1
        files = []

    for line in out.splitlines():
        if line.startswith("\x01"):
            flush()
            author, ts = line[1:].split("\x02")
            ts = int(ts)
            head_ts = head_ts or ts
        elif line.strip():
            files.append(line.strip())
    flush()
    return churn, {f: len(a) for f, a in authors.items()}, last_ts, pair, count, head_ts


# --------------------------------------------------------------------------- #
# Ranking + coupling                                                          #
# --------------------------------------------------------------------------- #

def pctile(values, v):
    """Mid-rank percentile: ties share the middle of their band, and the top value
    reports near 100 rather than an artificially low number."""
    if not values:
        return 0
    below = sum(1 for x in values if x < v)
    equal = sum(1 for x in values if x == v)
    return round(100 * (below + 0.5 * equal) / len(values))


def attach_percentiles(recs):
    sigs = ["loc", "largest_symbol_lines", "longest_func_lines", "max_nesting",
            "churn", "hotspot", "god_ratio", "density"]
    by_lang = defaultdict(list)
    for r in recs:
        by_lang[r.lang].append(r)
    for group in by_lang.values():
        pools = {s: [getattr(r, s) for r in group] for s in sigs}
        for r in group:
            r.pct = {s: pctile(pools[s], getattr(r, s)) for s in sigs}


def dist(values):
    if not values:
        return {"p50": 0, "p90": 0, "p99": 0, "max": 0}
    sv = sorted(values)
    q = lambda p: sv[min(len(sv) - 1, int(p * len(sv)))]
    return {"p50": q(.5), "p90": q(.9), "p99": q(.99), "max": sv[-1]}


def module(path, depth):
    parts = Path(path).parts
    return "/".join(parts[:depth]) if len(parts) > depth else "/".join(parts[:-1]) or "."


# --------------------------------------------------------------------------- #
# Render                                                                       #
# --------------------------------------------------------------------------- #

def pp(v):
    return f"{v:>3}"


def render_md(recs, cov, since_days, commits, coupling, top):
    L, by_lang = [], defaultdict(list)
    for r in recs:
        by_lang[r.lang].append(r)
    L.append("# Codebase audit\n")
    L.append("_Signal for judgment, not a gate. Sizes are proxies; brace/indent spans are approximate._\n")
    langs = ", ".join(f"{k} {len(v)}" for k, v in sorted(by_lang.items()))
    L.append(f"- Files: {len(recs)}  ·  non-blank LOC: {sum(r.loc for r in recs):,}  ·  "
             f"git window: {since_days}d ({commits} commits)")
    L.append(f"- Languages: {langs}")
    L.append(f"- Roots: {', '.join(sorted(cov['roots']))}")
    skip = []
    if cov["generated"]:
        skip.append(f"{cov['generated']} generated")
    if cov["skipped_big"]:
        skip.append(f"{cov['skipped_big']} file(s) >{MAX_FILE_BYTES // 1000}KB")
    if skip:
        L.append(f"- Skipped: {'; '.join(skip)}")
    L.append("")

    L.append("## Distributions (per language)\n")
    L.append("| lang | files | LOC p50/p90/p99/max | maxFn p90/max | nest p90/max | dens p50/p90/max | churn p90/max |")
    L.append("|---|--:|---|---|---|---|---|")
    for lang, g in sorted(by_lang.items()):
        dl, df = dist([r.loc for r in g]), dist([r.longest_func_lines for r in g])
        dn, dd, dc = dist([r.max_nesting for r in g]), dist([r.density for r in g]), dist([r.churn for r in g])
        L.append(f"| {lang} | {len(g)} | {dl['p50']}/{dl['p90']}/{dl['p99']}/{dl['max']} | {df['p90']}/{df['max']} "
                 f"| {dn['p90']}/{dn['max']} | {dd['p50']}/{dd['p90']}/{dd['max']} | {dc['p90']}/{dc['max']} |")

    L.append(f"\n## Attention leaderboard (top {top} by hotspot = LOC x churn)\n")
    L.append("Percentiles are within-language. `god%` = biggest symbol's share of file; "
             "`maxFn` = biggest single function; `decls` = top-level + nested symbols.\n")
    L.append("| file | LOC | LOC&deg; | maxSym | god% | maxFn | decls | c/l | nest&deg; | churn&deg; | last |")
    L.append("|---|--:|--:|---|--:|---|--:|--:|--:|--:|--:|")
    for r in sorted(recs, key=lambda r: (r.hotspot, r.loc), reverse=True)[:top]:
        last = f"{r.last_touched_days}d" if r.last_touched_days is not None else "-"
        sym = f"{r.largest_symbol} ({r.largest_symbol_lines})" if r.largest_symbol else "-"
        fn = f"{r.longest_func} ({r.longest_func_lines})" if r.longest_func else "-"
        L.append(f"| `{r.path}` | {r.loc} | {pp(r.pct['loc'])} | {sym} | {int(r.god_ratio*100)} | {fn} | {r.n_decls} "
                 f"| {r.density} | {pp(r.pct['max_nesting'])} | {pp(r.pct['churn'])} | {last} |")

    gods = sorted([r for r in recs if r.god_ratio >= .5 and r.largest_symbol_lines >= 60],
                  key=lambda r: r.largest_symbol_lines, reverse=True)[:top]
    if gods:
        L.append("\n## God-symbol files (one symbol is most of the file)\n")
        L.append("| file | symbol | symbol LOC | biggest fn | file LOC | god% |")
        L.append("|---|---|--:|---|--:|--:|")
        for r in gods:
            fn = f"{r.longest_func} ({r.longest_func_lines})" if r.longest_func else "-"
            L.append(f"| `{r.path}` | {r.largest_symbol} | {r.largest_symbol_lines} | {fn} | {r.loc} | {int(r.god_ratio*100)} |")

    if coupling:
        L.append("\n## Temporal coupling (co-change ≥ 50%, support ≥ 4)\n")
        L.append("Files that change together. Cross-module pairs (&starf;) suggest a boundary the tree doesn't show.\n")
        L.append("| file A | file B | co-changes | A&rarr;B | B&rarr;A | |")
        L.append("|---|---|--:|--:|--:|:-:|")
        for c in coupling[:top]:
            L.append(f"| `{c['a']}` | `{c['b']}` | {c['n']} | {int(c['ab']*100)}% | {int(c['ba']*100)}% "
                     f"| {'&starf;' if c['cross'] else ''} |")

    L.append("\n---\n_How to read: start at the leaderboard. High LOC&deg; + low god% (or small `maxFn` + many "
             "`decls`) = big but flat — a registry of small parts, often fine. High god% with a large `maxFn`, "
             "or high `nest&deg;` = one symbol/function eating the file: a refactor candidate. High churn&deg; = "
             "where bugs accrue. Coupling stars = candidate module splits. Decide per file; nothing here is a verdict._")
    return "\n".join(L)


# --------------------------------------------------------------------------- #
# Changed-files view (post-commit heads-up)                                    #
# --------------------------------------------------------------------------- #

def changed_files(repo, staged):
    """Files to spotlight: the staged diff (pre-commit, the commit being made) or
    HEAD's commit (post-hoc). staged=True has no churn self-inflation since the
    commit doesn't exist yet."""
    cmd = (["git", "diff", "--cached", "--name-only"] if staged
           else ["git", "diff-tree", "--no-commit-id", "--name-only", "-r", "--root", "HEAD"])
    try:
        out = subprocess.run(cmd, cwd=repo, capture_output=True, text=True, timeout=30)
        return [l.strip() for l in out.stdout.splitlines() if l.strip()] if out.returncode == 0 else []
    except (subprocess.SubprocessError, OSError):
        return []


def outlier_reasons(r):
    """Transparent, evidence-not-verdict heads-up: which signals put this file in
    its language's top decile (or gave it a big single function). Never a gate."""
    reasons = []
    if r.pct.get("loc", 0) >= 90:
        reasons.append(f"p{r.pct['loc']} LOC")
    if r.pct.get("max_nesting", 0) >= 90:
        reasons.append(f"p{r.pct['max_nesting']} nesting")
    if r.pct.get("churn", 0) >= 90:
        reasons.append(f"p{r.pct['churn']} churn")
    if r.god_ratio >= 0.6 and r.longest_func_lines >= 60:
        reasons.append(f"god {int(r.god_ratio*100)}% / maxFn {r.longest_func}({r.longest_func_lines})")
    return reasons


def render_changed(recs, changed):
    by_path = {r.path: r for r in recs}
    src = [by_path[p] for p in changed if p in by_path]
    flagged = [(r, rs) for r in src if (rs := outlier_reasons(r))]
    flagged.sort(key=lambda x: x[0].hotspot, reverse=True)
    other = len(changed) - len(src)
    head = f"codebase-audit · {len(src)} source file(s) changed" + (f", {other} other" if other else "")
    if not flagged:
        return f"{head} — all within normal ranges (advisory, non-blocking)"
    L = [f"{head} (advisory, non-blocking — `audit.py` for the full map):"]
    for r, rs in flagged:
        ctx = []
        if r.largest_symbol:
            ctx.append(f"maxSym {r.largest_symbol}({r.largest_symbol_lines})")
        ctx.append(f"{r.n_decls} decls")
        L.append(f"  ⚠ {r.path}")
        L.append(f"      {' · '.join(rs)}  ·  {' · '.join(ctx)}")
    if len(src) > len(flagged):
        L.append(f"  {len(src) - len(flagged)} other touched file(s) within normal ranges")
    return "\n".join(L)


# --------------------------------------------------------------------------- #
# Main                                                                         #
# --------------------------------------------------------------------------- #

def main():
    ap = argparse.ArgumentParser(description="Codebase health audit (signal, not a gate).")
    ap.add_argument("--path", action="append", help="scope to a subtree (repeatable, prefix match)")
    ap.add_argument("--lang", help=f"restrict to one language: {'|'.join(sorted(LANGS))}")
    ap.add_argument("--since-days", type=int, default=90, help="git window for churn/coupling (default 90)")
    ap.add_argument("--top", type=int, default=15, help="rows per leaderboard (default 15)")
    ap.add_argument("--module-depth", type=int, default=2, help="path segments that define a 'module' for coupling (default 2)")
    ap.add_argument("--changed", action="store_true", help="heads-up scoped to HEAD's commit, flagged if structural outliers (non-blocking)")
    ap.add_argument("--staged", action="store_true", help="like --changed but scoped to the staged diff (for a pre-commit hook)")
    ap.add_argument("--json", action="store_true", help="emit machine-readable JSON")
    ap.add_argument("--repo", default=".", help="repo root (default cwd)")
    args = ap.parse_args()
    if args.lang and args.lang not in LANGS:
        sys.exit(f"--lang must be one of {sorted(LANGS)}")

    repo = Path(args.repo).resolve()
    paths = [p.replace("\\", "/").rstrip("/") for p in (args.path or [])]

    found, cov = discover(repo, paths, args.lang)
    recs = [r for rel, lang in found if (r := analyze_file(repo, rel, lang))]
    if not recs:
        sys.exit("No source files found. Is this a git repo? Try --path or --repo.")

    churn, authors, last_ts, pair, count, head_ts = git_history(repo, args.since_days)
    by_path = {r.path: r for r in recs}
    for r in recs:
        r.churn, r.authors = churn.get(r.path, 0), authors.get(r.path, 0)
        if r.path in last_ts and head_ts:
            r.last_touched_days = max(0, (head_ts - last_ts[r.path]) // 86400)
        r.hotspot = r.loc * r.churn
    attach_percentiles(recs)

    if args.changed or args.staged:
        print(render_changed(recs, changed_files(repo, args.staged)))
        return

    coupling = []
    for (a, b), n in pair.items():
        if n < COUPLING_SUPPORT or a not in by_path or b not in by_path:
            continue
        ab, ba = n / (count.get(a, n) or n), n / (count.get(b, n) or n)
        if max(ab, ba) < COUPLING_RATIO:
            continue
        coupling.append({"a": a, "b": b, "n": n, "ab": round(ab, 2), "ba": round(ba, 2),
                         "cross": module(a, args.module_depth) != module(b, args.module_depth)})
    coupling.sort(key=lambda c: (c["cross"], c["n"]), reverse=True)
    commits = commit_count(repo, args.since_days)

    if args.json:
        print(json.dumps({
            "files": [vars(r) for r in recs], "coupling": coupling,
            "meta": {"since_days": args.since_days, "commits": commits,
                     "languages": dict(cov["by_lang"]), "generated": cov["generated"],
                     "skipped_big": cov["skipped_big"]},
        }, indent=2, default=str))
    else:
        print(render_md(recs, cov, args.since_days, commits, coupling, args.top))


def commit_count(repo, since_days):
    try:
        return int(subprocess.run(
            ["git", "rev-list", "--count", "--no-merges", f"--since={since_days} days ago", "HEAD"],
            cwd=repo, capture_output=True, text=True, timeout=30).stdout.strip() or 0)
    except (subprocess.SubprocessError, OSError, ValueError):
        return 0


if __name__ == "__main__":
    main()
